version: "3.9"

services:
  backend:
    build:
      context: https://github.com/avito-tech/tech-internship.git#main:Tech%20Internships/Frontend/Frontend-trainee-assignment-spring-2025/server
      dockerfile: Dockerfile
    container_name: tasktracker-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasktracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  default:
    name: tasktracker