services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: .  
      dockerfile: Dockerfile.frontend  
    container_name: tasktracker
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge